runtime: nodejs18

handlers:
  - url: /favicon\.png
    static_files: favicon.png
    upload: favicon\.png

  - url: /www/images
    static_dir: www/images

  - url: /www/scripts
    static_dir: www/scripts

  - url: /www/styles
    static_dir: www/styles

  - url: /.*
    static_files: index.html
    upload: index.html
    secure: never

  - url: /(.*)
    script: auto
    secure: never
